### ISSUE TITLE
^^^^^ characters in statusline

### ISSUE THREAD

**Issue by oblitum** [UnikMask/iroh-vim#2]
Hi, really nice colorscheme, thanks for it. I have an issue with it that when I have a window split, the current window statusline gets filled with ^^^^^ characters. I use lightline, would be great if iroh supported it too (like there's in [vim-deep-space](https://github.com/tyrannicaltoucan/vim-deep-space/tree/master/autoload) and [underword.vim](https://github.com/atchim/underworld.vim/tree/master/autoload) for example), currently I'm using srcery_alter lightline theme.

**Comment by oblitum** [comment]
![img-2020-12-22-185819](https://user-images.githubusercontent.com/1269815/102936842-b0a7e900-4487-11eb-9c98-30d38298fb58.png)

**Comment by UnikMask** [comment]
I can confirm it not only does this in Lightline but also in Airline. I'm right now trying to find where in the code the issue comes from, but you can also try looking into the issue if you have the time.

In any case thanks for the heads up!

**Comment by UnikMask** [comment]
Talked too quick - I just found and fixed the issue with latest commit - Please check if you still see some ^^^ on your status line, then go ahead and close the issue.

Also, about lightline theme, I don't personally use it, but I'll try theming it in the next few days.

**Comment by oblitum** [comment]
k, thanks for the fix, just tried. Looking forward for lightline theme :)
