### ISSUE TITLE
CursorLine fg color

### ISSUE THREAD

**Issue by francescomarocchi** [UnikMask/iroh-vim#3]
Absolutely awesome colorscheme!

Just a problem I'm having with currently selected line.

`call s:Highlight('CursorLine', s:bg, s:clay0)` 

could be better something like;

`call s:Highlight('CursorLine', s:none, s:clay0)`

It's nearly impossibile to read the line using s:bg as foreground color...

Thanks again for the beautiful color scheme 👍

**Comment by UnikMask** [comment]
Yo!
Just escaped Emacs and am currently recoloring the colorscheme. I think I didn´t understand what CursorLine did at the time, but now I've updated it and multiple other components. I invite you to try out the changes. Closing this issue now.
